import logging

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional

from app.api.deps import get_current_user, get_db
from app.models.user import User
from app.schemas.quiz import QuizGenerateRequest, QuizResponse
from app.services.quiz_service import generate_quiz, get_quiz_by_id, list_user_quizzes

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/quiz", tags=["quiz"])


class QuizListItem(BaseModel):
    quiz_id: str
    session_id: str
    doc_filename: str
    subject: str
    topic: Optional[str]
    difficulty: str
    total_questions: int
    created_at: str


@router.post("/generate", response_model=QuizResponse, status_code=201)
async def generate_quiz_endpoint(
    request: QuizGenerateRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> QuizResponse:
    """Generate an adaptive quiz from a previously ingested document."""
    try:
        return await generate_quiz(request, current_user.id, db)
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Quiz generation error for doc_id=%s", request.doc_id)
        raise HTTPException(
            status_code=500,
            detail="Quiz generation failed — the AI model returned an unexpected response. Please try again.",
        ) from exc


@router.get("", response_model=list[QuizListItem])
async def get_user_quizzes(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> list[QuizListItem]:
    """List all quizzes generated by the current user."""
    return await list_user_quizzes(current_user.id, db)


@router.get("/{quiz_id}", response_model=QuizResponse)
async def get_quiz(
    quiz_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> QuizResponse:
    """Retrieve a previously generated quiz by its quiz_id."""
    return await get_quiz_by_id(quiz_id, current_user.id, db)
